# Config file for automatic testing at travis-ci.org

language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy

install:
  - pip install --upgrade pip
  - pip install --upgrade pytest
  - pip install poetry

script:
  - poetry install
  - poetry add coveralls
  - poetry run coverage run --source=pytest_datafiles runtests.py

after_success:
  - poetry run coveralls
